apiVersion: skaffold/v1
kind: Config
build:
  artifacts:
    - image: jamataran/aircev
      context: ../acceso-a-datos-simulacro1
      jib: {}
  tagPolicy:
    envTemplate:
      template: '{{.IMAGE_NAME}}:latest'
deploy:
  kustomize: {}
